name: CI
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  test:
    strategy:
      matrix:
        node: ['14.x', '16.x']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - run: npm i -g pnpm@6.20.3
    - run: pnpm install --frozen-lockfile
    - run: yarn lint
    - run: yarn build
    - run: yarn test
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: |
          cd packages/docs
          yarn install --frozen-lockfile
          yarn build
      - name: Deploy
        uses: nwtgck/actions-netlify@v1.2
        with:
          enable-commit-comment: true
          enable-pull-request-comment: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          overwrites-pull-request-comment: true
          production-deploy: ${{ github.event_name != 'pull_request' }}
          publish-dir: packages/docs/build
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
